function out = model
%
% water.m
%
% Model exported on Mar 6 2020, 21:03 by COMSOL 5.4.0.388.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('C:\Users\hasee\Desktop');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 2);

model.component('comp1').mesh.create('mesh1');

model.component('comp1').physics.create('spf', 'LaminarFlow', 'geom1');

model.study.create('std1');
model.study('std1').setGenConv(true);
model.study('std1').create('time', 'Transient');
model.study('std1').feature('time').activate('spf', true);

model.param.set('U_mean', '1[m/s]');
model.param.descr('U_mean', [native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'57' '47'}), 'unicode')  native2unicode(hex2dec({'6d' '41'}), 'unicode')  native2unicode(hex2dec({'51' '65'}), 'unicode')  native2unicode(hex2dec({'90' '1f'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ]);

model.func.create('step1', 'Step');
model.func('step1').set('location', 0.1);

model.component('comp1').geom('geom1').create('r1', 'Rectangle');
model.component('comp1').geom('geom1').feature('r1').set('size', [2.2 2.2]);
model.component('comp1').geom('geom1').run('r1');
model.component('comp1').geom('geom1').run('r1');
model.component('comp1').geom('geom1').create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('c1').set('r', 0.2);
model.component('comp1').geom('geom1').run('c1');
model.component('comp1').geom('geom1').feature('c1').set('pos', [1.1 1.1]);
model.component('comp1').geom('geom1').run('c1');
model.component('comp1').geom('geom1').run('c1');
model.component('comp1').geom('geom1').create('dif1', 'Difference');
model.component('comp1').geom('geom1').feature('dif1').selection('input').set({'r1'});
model.component('comp1').geom('geom1').feature('dif1').selection('input2').set({'c1'});
model.component('comp1').geom('geom1').run('dif1');

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material('mat1').propertyGroup('def').func.create('eta', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('Cp', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('rho', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('k', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('cs', 'Interpolation');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an1', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an2', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an3', 'Analytic');
model.component('comp1').material('mat1').label('Water');
model.component('comp1').material('mat1').set('family', 'water');
model.component('comp1').material('mat1').set('groups', {'liquids' 'Liquids'});
model.component('comp1').material('mat1').propertyGroup('def').label('Basic');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').label('Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('pieces', {'273.15' '413.15' '1.3799566804-0.021224019151*T^1+1.3604562827E-4*T^2-4.6454090319E-7*T^3+8.9042735735E-10*T^4-9.0790692686E-13*T^5+3.8457331488E-16*T^6'; '413.15' '553.75' '0.00401235783-2.10746715E-5*T^1+3.85772275E-8*T^2-2.39730284E-11*T^3'});
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').label('Piecewise 2');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('pieces', {'273.15' '553.75' '12010.1471-80.4072879*T^1+0.309866854*T^2-5.38186884E-4*T^3+3.62536437E-7*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').label('Piecewise 3');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('smooth', 'contd1');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('pieces', {'273.15' '293.15' '0.000063092789034*T^3-0.060367639882855*T^2+18.9229382407066*T-950.704055329848'; '293.15' '373.15' '0.000010335053319*T^3-0.013395065634452*T^2+4.969288832655160*T+432.257114008512'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.component('comp1').material('mat1').propertyGroup('def').func('k').label('Piecewise 4');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('pieces', {'273.15' '553.75' '-0.869083936+0.00894880345*T^1-1.58366345E-5*T^2+7.97543259E-9*T^3'});
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').label('Interpolation');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('table', {'273' '1403';  ...
'278' '1427';  ...
'283' '1447';  ...
'293' '1481';  ...
'303' '1507';  ...
'313' '1526';  ...
'323' '1541';  ...
'333' '1552';  ...
'343' '1555';  ...
'353' '1555';  ...
'363' '1550';  ...
'373' '1543'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('interp', 'piecewisecubic');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('fununit', 'm/s');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').label('Analytic ');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('expr', '-1/rho(T)*d(rho(T),T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('fununit', '1/K');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').label('Analytic 2');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('funcname', 'gamma_w');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('expr', '1+(T/Cp(T))*(alpha_p(T)*cs(T))^2');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('fununit', '1');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an3').label('Analytic 3');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('funcname', 'muB');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('expr', '2.79*eta(T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('an3').set('plotargs', {'T' '273.15' '553.75'});
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.component('comp1').material('mat1').propertyGroup('def').set('bulkviscosity', '');
model.component('comp1').material('mat1').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('ratioofspecificheat', 'gamma_w(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('electricconductivity', {'5.5e-6[S/m]' '0' '0' '0' '5.5e-6[S/m]' '0' '0' '0' '5.5e-6[S/m]'});
model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('soundspeed', 'cs(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(T)' '0' '0' '0' 'alpha_p(T)' '0' '0' '0' 'alpha_p(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.component('comp1').material('mat1').propertyGroup('def').addInput('temperature');
model.component('comp1').material('mat1').set('family', 'water');

model.component('comp1').geom('geom1').run;

model.component('comp1').physics('spf').create('inl1', 'InletBoundary', 1);
model.component('comp1').physics('spf').feature('inl1').selection.set([1]);
model.component('comp1').physics('spf').feature('inl1').set('U0in', 'U_mean*6*s*(1-s)*step1(t[1/s])');
model.component('comp1').physics('spf').create('out1', 'OutletBoundary', 1);
model.component('comp1').physics('spf').feature('out1').selection.set([4]);

model.component('comp1').mesh('mesh1').autoMeshSize(3);
model.component('comp1').mesh('mesh1').run;

model.study('std1').feature('time').set('tlist', 'range(0,0.2,3.4) range(3.5,0.02,7)');

model.sol.create('sol1');
model.sol('sol1').study('std1');

model.study('std1').feature('time').set('notlistsolnum', 1);
model.study('std1').feature('time').set('notsolnum', '1');
model.study('std1').feature('time').set('listsolnum', 1);
model.study('std1').feature('time').set('solnum', '1');

model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'time');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'time');
model.sol('sol1').create('t1', 'Time');
model.sol('sol1').feature('t1').set('tlist', 'range(0,0.2,3.4) range(3.5,0.02,7)');
model.sol('sol1').feature('t1').set('plot', 'off');
model.sol('sol1').feature('t1').set('plotgroup', 'Default');
model.sol('sol1').feature('t1').set('plotfreq', 'tout');
model.sol('sol1').feature('t1').set('probesel', 'all');
model.sol('sol1').feature('t1').set('probes', {});
model.sol('sol1').feature('t1').set('probefreq', 'tsteps');
model.sol('sol1').feature('t1').set('rtol', 0.005);
model.sol('sol1').feature('t1').set('atolglobalmethod', 'scaled');
model.sol('sol1').feature('t1').set('atolglobalfactor', 0.05);
model.sol('sol1').feature('t1').set('atolglobalvaluemethod', 'factor');
model.sol('sol1').feature('t1').set('atolmethod', {'comp1_p' 'scaled' 'comp1_u' 'global'});
model.sol('sol1').feature('t1').set('atolvaluemethod', {'comp1_p' 'factor' 'comp1_u' 'factor'});
model.sol('sol1').feature('t1').set('atolfactor', {'comp1_p' '1' 'comp1_u' '0.1'});
model.sol('sol1').feature('t1').set('estrat', 'exclude');
model.sol('sol1').feature('t1').set('maxorder', 2);
model.sol('sol1').feature('t1').set('stabcntrl', true);
model.sol('sol1').feature('t1').set('bwinitstepfrac', '0.01');
model.sol('sol1').feature('t1').set('control', 'time');
model.sol('sol1').feature('t1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('t1').feature('fc1').set('jtech', 'once');
model.sol('sol1').feature('t1').feature('fc1').set('damp', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('stabacc', 'aacc');
model.sol('sol1').feature('t1').feature('fc1').set('aaccdim', 5);
model.sol('sol1').feature('t1').feature('fc1').set('aaccmix', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('aaccdelay', 1);
model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.5);
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 8);
model.sol('sol1').feature('t1').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('t1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('t1').feature('fc1').set('jtech', 'once');
model.sol('sol1').feature('t1').feature('fc1').set('damp', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('stabacc', 'aacc');
model.sol('sol1').feature('t1').feature('fc1').set('aaccdim', 5);
model.sol('sol1').feature('t1').feature('fc1').set('aaccmix', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('aaccdelay', 1);
model.sol('sol1').feature('t1').feature('fc1').set('ntolfact', 0.5);
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 8);
model.sol('sol1').feature('t1').feature.remove('fcDef');
model.sol('sol1').attach('std1');
model.sol('sol1').feature('t1').set('tstepsbdf', 'intermediate');

model.result.dataset('dset1').set('geom', 'geom1');
model.result.create('pg1', 'PlotGroup2D');
model.result('pg1').label([native2unicode(hex2dec({'90' '1f'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ' (spf)']);
model.result('pg1').set('frametype', 'spatial');
model.result('pg1').set('data', 'dset1');
model.result('pg1').feature.create('surf1', 'Surface');
model.result('pg1').feature('surf1').label([native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'97' '62'}), 'unicode') ]);
model.result('pg1').feature('surf1').set('smooth', 'internal');
model.result('pg1').feature('surf1').set('data', 'parent');
model.result.create('pg2', 'PlotGroup2D');
model.result('pg2').label([native2unicode(hex2dec({'53' '8b'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (spf)']);
model.result('pg2').set('frametype', 'spatial');
model.result('pg2').set('data', 'dset1');
model.result('pg2').feature.create('con1', 'Contour');
model.result('pg2').feature('con1').label([native2unicode(hex2dec({'7b' '49'}), 'unicode')  native2unicode(hex2dec({'50' '3c'}), 'unicode')  native2unicode(hex2dec({'7e' 'bf'}), 'unicode') ]);
model.result('pg2').feature('con1').set('expr', 'p');
model.result('pg2').feature('con1').set('number', 40);
model.result('pg2').feature('con1').set('smooth', 'internal');
model.result('pg2').feature('con1').set('data', 'parent');
model.result.remove('pg2');
model.result.remove('pg1');

model.component('comp1').geom('geom1').feature('r1').set('size', [2.2 1]);
model.component('comp1').geom('geom1').run;

model.result.dataset('dset1').set('geom', 'geom1');
model.result.create('pg1', 'PlotGroup2D');
model.result('pg1').label([native2unicode(hex2dec({'90' '1f'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ' (spf)']);
model.result('pg1').set('showlooplevel', {'off' 'off' 'off'});
model.result('pg1').set('frametype', 'spatial');
model.result('pg1').set('data', 'dset1');
model.result('pg1').feature.create('surf1', 'Surface');
model.result('pg1').feature('surf1').label([native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'97' '62'}), 'unicode') ]);
model.result('pg1').feature('surf1').set('smooth', 'internal');
model.result('pg1').feature('surf1').set('data', 'parent');
model.result.create('pg2', 'PlotGroup2D');
model.result('pg2').label([native2unicode(hex2dec({'53' '8b'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (spf)']);
model.result('pg2').set('showlooplevel', {'off' 'off' 'off'});
model.result('pg2').set('frametype', 'spatial');
model.result('pg2').set('data', 'dset1');
model.result('pg2').feature.create('con1', 'Contour');
model.result('pg2').feature('con1').label([native2unicode(hex2dec({'7b' '49'}), 'unicode')  native2unicode(hex2dec({'50' '3c'}), 'unicode')  native2unicode(hex2dec({'7e' 'bf'}), 'unicode') ]);
model.result('pg2').feature('con1').set('expr', 'p');
model.result('pg2').feature('con1').set('number', 40);
model.result('pg2').feature('con1').set('smooth', 'internal');
model.result('pg2').feature('con1').set('data', 'parent');

model.sol('sol1').runAll;

model.result('pg1').run;

model.component('comp1').geom('geom1').feature('r1').set('size', [2.2 2.2]);
model.component('comp1').geom('geom1').run('r1');
model.component('comp1').geom('geom1').run('c1');
model.component('comp1').geom('geom1').run('dif1');
model.component('comp1').geom('geom1').feature('r1').set('size', [2.2 1.5]);
model.component('comp1').geom('geom1').run('r1');
model.component('comp1').geom('geom1').feature('c1').set('pos', [1.1 0.75]);
model.component('comp1').geom('geom1').run('c1');
model.component('comp1').geom('geom1').run('dif1');

model.component('comp1').mesh('mesh1').autoMeshSize(2);
model.component('comp1').mesh('mesh1').run;

model.sol('sol1').runAll;

model.result('pg1').run;

model.component('comp1').geom('geom1').feature('r1').set('size', [2.2 2.2]);
model.component('comp1').geom('geom1').run('r1');
model.component('comp1').geom('geom1').run('dif1');
model.component('comp1').geom('geom1').run('dif1');
model.component('comp1').geom('geom1').feature('c1').set('pos', [1.1 1.1]);
model.component('comp1').geom('geom1').run('c1');
model.component('comp1').geom('geom1').run('dif1');
model.component('comp1').geom('geom1').run;

model.component('comp1').mesh('mesh1').run;

model.sol('sol1').runAll;

model.result('pg1').run;
model.result('pg1').create('ptr1', 'ParticleMass');
model.result('pg1').feature('ptr1').set('mass', '4*pi/3*1e-9');
model.result('pg1').feature('ptr1').set('velstartx', 'u');
model.result('pg1').feature('ptr1').set('velstarty', 'v');
model.result('pg1').feature('ptr1').set('xcoord', 'range(0.1,0.05,0.3)');
model.result('pg1').feature('ptr1').set('ycoord', 0);
model.result('pg1').feature('ptr1').set('dropmethod', 'freq');
model.result('pg1').feature('ptr1').set('tstartactive', true);
model.result('pg1').feature('ptr1').set('tstart', 3.6);
model.result('pg1').feature('ptr1').set('dropfreq', 0.4);
model.result('pg1').feature('ptr1').set('linetype', 'none');
model.result('pg1').feature('ptr1').set('pointtype', 'point');
model.result('pg1').run;
model.result('pg1').feature('ptr1').set('pointdom', 'disappear');
model.result('pg1').run;
model.result('pg2').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg2').run;
model.result('pg1').run;
model.result('pg1').feature('surf1').set('resolution', 'extrafine');
model.result.export.create('data1', 'Data');
model.result.export('data1').set('filename', 'C:\Users\hasee\Desktop\Untitled.txt');
model.result.export('data1').run;
model.result.report.create('rpt1', 'Report');
model.result.report('rpt1').set('templatesource', 'complete');
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'fd'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'96' '36'}), 'unicode')  native2unicode(hex2dec({'8d' 'c3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').create('func1', 'Functions');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').feature('func1').set('noderef', 'step1');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'Water');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'5c' '42'}), 'unicode')  native2unicode(hex2dec({'6d' '41'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'spf');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'90' '1f'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'53' '8b'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').feature('pg1').set('noderef', 'pg2');
model.result.report('rpt1').run;
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'fd'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'96' '36'}), 'unicode')  native2unicode(hex2dec({'8d' 'c3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').create('func1', 'Functions');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').feature('func1').set('noderef', 'step1');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'Water');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'5c' '42'}), 'unicode')  native2unicode(hex2dec({'6d' '41'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'spf');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'90' '1f'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'53' '8b'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').feature('pg1').set('noderef', 'pg2');
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'fd'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'96' '36'}), 'unicode')  native2unicode(hex2dec({'8d' 'c3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').create('func1', 'Functions');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').feature('func1').set('noderef', 'step1');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'Water');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'5c' '42'}), 'unicode')  native2unicode(hex2dec({'6d' '41'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'spf');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'90' '1f'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'53' '8b'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').feature('pg1').set('noderef', 'pg2');
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'fd'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'96' '36'}), 'unicode')  native2unicode(hex2dec({'8d' 'c3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').create('func1', 'Functions');
model.result.report('rpt1').feature('sec1').feature('sec2').feature('sec1').feature('func1').set('noderef', 'step1');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'Water');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'5c' '42'}), 'unicode')  native2unicode(hex2dec({'6d' '41'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'spf');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'90' '1f'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'53' '8b'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode') ' (spf)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec2').feature('pg1').set('noderef', 'pg2');
model.result.export.create('plot1', 'Plot');
model.result('pg1').feature('ptr1').active(false);
model.result('pg1').feature('ptr1').active(true);
model.result.export('plot1').set('filename', 'C:\Users\hasee\Desktop\Untitled.txt');
model.result.export('plot1').run;
model.result.report('rpt1').set('format', 'docx');
model.result.report('rpt1').set('filename', 'C:\Users\hasee\Desktop\Untitled.docx');
model.result.report('rpt1').set('imagesize', 'xlarge');
model.result.report('rpt1').run;

out = model;
